### ISSUE TITLE
大神,有没有支持 h5(微信扫描打开的H5), 小程序, app 的多端图片缩放组件? 

### ISSUE THREAD

**Issue by yanglei9999** [xiaowang1314/uniapp-plugin-collections#13]
近期学习 uniapp
看过10几个例子, 一般都是 小程序和 app 图片缩放好使, 
h5 的一般都没有效果, 偶尔碰到有效果的也是, 整个 h5 页面整体放大, 用微信扫描打开的 h5 页面,就没碰到过能图片缩放的, 包括官方的例子

希望大神, 如果知道能分享一下 , 谢谢了

**Comment by xiaowang1314** [comment]
暂时没有
