### ISSUE TITLE
有什么问题可以在这里讨论哦

### ISSUE THREAD

**Issue by xiaowang1314** [xiaowang1314/uniapp-plugin-collections#3]

**Comment by Yuwenxuan-wx** [comment]
模糊搜索引入报错。用的例子，其他没改
![image](https://user-images.githubusercontent.com/26829431/72148593-2bddcf80-33dc-11ea-85cd-db614cc92f2e.png)

**Comment by lauralxj** [comment]
如何做到高度随内容自适应啊，右边内容多的时候就不在一行，错位了

**Comment by lauralxj** [comment]
![mmexport1584893008430(1)](https://user-images.githubusercontent.com/12034817/77254124-11f12080-6c9a-11ea-93be-ffc62bdcc9a7.jpg)
如何做到高度随内容自适应啊，右边内容多的时候就不在一行，错位了

**Comment by pikaqiuqiu** [comment]
输入错误密码后，再输入小数点，第一次点击输入不进去，第二次点击小数点，gerVal获取到的value是上一次的数字，此时再输入就输入不进去任何字符，getVal无法继续触发

**Comment by xiaowang1314** [comment]
@pikaqiuqiu getVal只有输入6位才会触发

**Comment by LaiyuboTeam11** [comment]
你好 我想问一下在vue页面中如何调用clear的方法呢
