### ISSUE TITLE
有没有内容从左往右的瀑布流呢。

### ISSUE THREAD

**Issue by windExplorer** [xiaowang1314/uniapp-plugin-collections#6]
瀑布流好的实现方式百度了好久，利用css3实现的有flex，有Multi-columns还有Grid，但都有一个通病，就是数据都是从上往下，而不是从左往右。
意思是数据列的变化是1,2,1,2或者1,2,3,4,1,2,3,4等等这样交替，而不是先排列完第一列再来排列第二列，我滑到下面，如果数据有新的变化，新数据是在最后一列从上往下排列，这样我又得滑上去。很难受。
不知道有没有什么好的见解。

**Comment by xiaowang1314** [comment]
> 瀑布流好的实现方式百度了好久，利用css3实现的有flex，有Multi-columns还有Grid，但都有一个通病，就是数据都是从上往下，而不是从左往右。
> 意思是数据列的变化是1,2,1,2或者1,2,3,4,1,2,3,4等等这样交替，而不是先排列完第一列再来排列第二列，我滑到下面，如果数据有新的变化，新数据是在最后一列从上往下排列，这样我又得滑上去。很难受。
> 不知道有没有什么好的见解。

https://github.com/xiaowang1314/uniapp-plugin-collections/blob/master/markdowns/waterfall2.md

写了个案例，可以参考下
