### ISSUE TITLE
导入Hbuilder X 然后真机运行无法显示

### ISSUE THREAD

**Issue by sweet2o09** [xiaowang1314/uniapp-plugin-collections#8]
TypeError: $gwx is not a function
at file:///storage/emulated/0/Android/data/io.dcloud.HBuilder/apps/HBuilder/www/app-view.js:98:27 at uniapp://ready:182
webviewScriptError
$gwx is not a function
TypeError: $gwx is not a function
at file:///storage/emulated/0/Android/data/io.dcloud.HBuilder/apps/HBuilder/www/app-view.js:98:27 at uniapp://ready:182
Uncaught TypeError: $gwx is not a function at app-view.js:98
reportJSException >>>> exception function:createInstanceContext, exception:white screen cause create instanceContext failed,check js stack ->TypeError: $gwx is not a function. (In '$gwx('./app.wxml')', '$gwx' is undefined)
getTemplateInfo== template md5 c27b2672170a8c615b6273fb6fcb42ab length 2165189 base64 md5 wnsmchcKjGFbYnP7b8tCqw== response header {"templateSourceBase64MD5":["wnsmchcKjGFbYnP7b8tCqw=="],"templateSourceMD5":["c27b2672170a8c615b6273fb6fcb42ab"]}

**Comment by xiaowang1314** [comment]
整个项目clone下试试呢
